--BANK SYSTEM

DROP TABLE [TBL_TRANSFERS]

CREATE TABLE [TBL_ACCOUNTS] (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [OWNER] NVARCHAR(50) NOT NULL,
    [BALANCE] BIGINT NOT NULL,
    [CURRENCY] NVARCHAR(20) NOT NULL,
    [CREATED_AT] DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE [TBL_ENTRIES] (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [ACCOUNT_ID] BIGINT NOT NULL,
    [AMOUNT] BIGINT NOT NULL,
    [CREATED_AT] DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE [TBL_TRANSFERS] (
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY,
    [FROM_ACCOUNT_ID] BIGINT NOT NULL,
    [TO_ACCOUNT_ID] BIGINT NOT NULL,
    [AMOUNT] BIGINT NOT NULL,
    [CREATED_AT] DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO [TBL_ACCOUNTS] ([OWNER], [BALANCE],[CURRENCY]) VALUES ('ALI MRAD', 1500, 'DOLLAR');
INSERT INTO [TBL_ACCOUNTS] ([OWNER], [BALANCE],[CURRENCY]) VALUES ('AMIR MRAD', 100, 'DOLLAR');
INSERT INTO [TBL_ACCOUNTS] ([OWNER], [BALANCE],[CURRENCY]) VALUES ('ALI MR', 500, 'DOLLAR');
INSERT INTO [TBL_ACCOUNTS] ([OWNER], [BALANCE],[CURRENCY]) VALUES ('ALI SS', 700, 'DOLLAR');
INSERT INTO [TBL_ACCOUNTS] ([OWNER], [BALANCE],[CURRENCY]) VALUES ('ALI TT', 800, 'DOLLAR');
INSERT INTO [TBL_ACCOUNTS] ([OWNER], [BALANCE],[CURRENCY]) VALUES ('ALI FF', 900, 'DOLLAR');

SELECT *
FROM
[TBL_ACCOUNTS];


ALTER TABLE [TBL_ENTRIES]
ADD FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [TBL_ACCOUNTS] ([ID]);

ALTER TABLE [TBL_TRANSFERS]
ADD FOREIGN KEY ([FROM_ACCOUNT_ID]) REFERENCES [TBL_ACCOUNTS] ([ID]);

ALTER TABLE [TBL_TRANSFERS]
ADD FOREIGN KEY ([TO_ACCOUNT_ID]) REFERENCES [TBL_ACCOUNTS] ([ID]);

INSERT INTO [TBL_ENTRIES] ([ACCOUNT_ID],[AMOUNT]) VALUES ( 1,100);

ALTER TABLE [TBL_ACCOUNTS] ADD [ACTIVATED] BIT DEFAULT 1;

UPDATE [TBL_ACCOUNTS] SET [ACTIVATED]=1 WHERE [ID] = 9


EXECUTE [dbo].[INSERT_ENTRIES_AND_INCREMENT_AMOUNT_BALANCE] 
  200
  ,1

SELECT *
FROM
[TBL_ACCOUNTS]
WHERE [OWNER]='ALI FF';

EXEC [DBO].[GET_AMOUNT_OWNER] 1;

SELECT DBO.GET_SUM_ENTRIES_FOR_EACH_OWNER(1) 'SUM'
FROM [TBL_ENTRIES]
WHERE [ID] = 1; 


EXEC [DBO].[TRANSFER_FOM_ACCOUNT1_TO_ACCOUNT2]
2,
1,
250

SELECT [BALANCE]
FROM
[TBL_ACCOUNTS]
WHERE [ID] = 1;

EXEC [DBO].[TRANSFER_FOM_ACCOUNT1_TO_ACCOUNT2]
2,
1,
250

SELECT [BALANCE]
FROM
[TBL_ACCOUNTS]
WHERE [ID] = 2;

EXEC [dbo].[GET_FROM_TO_AMOUT_TRANSFER_OWNER] 5;

--FUNCTIONS TO RETURN THE SUM OF OWNER ENTRIES 

SELECT TOP 10 * 
FROM [TBL_TRANSFERS]
FOR JSON PATH;

CREATE INDEX index1 ON [TBL_ACCOUNTS] ([OWNER]);

EXEC DBO.DI_ACTIVATED_ACC 4;


EXECUTE [dbo].[INSERT_ENTRIES_AND_INCREMENT_AMOUNT_BALANCE] 
  200
  ,1

EXEC DBO.ACTIVATE_ACC 4;

SELECT  * 
FROM [TBL_ACCOUNTS]
WHERE [ID] =4